name: Release CI

on:
  release:
    types: [published]

jobs:
  validate-tag-format:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Validate version vs prerelease flag
      run: |
        VERSION="${{ github.event.release.tag_name }}"

        # Remove leading 'v' if present
        if [[ "$VERSION" == v* ]]; then
          VERSION="${VERSION:1}"
        fi

        if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(a|b|rc)[0-9]+$ ]]; then
            echo "GitHub release marked prerelease, but version is not a valid PEP440 prerelease"
            exit 1
          fi
        else
          if [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(a|b|rc)[0-9]+$ ]]; then
            echo "Stable release cannot use prerelease version"
            exit 1
          fi
        fi
  build:
    needs:
      - validate-tag-format
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0

      - name: Set up dependencies
        uses: ./.github/actions/setup-deps

      - name: Build, test and upload artifact
        uses: ./.github/actions/build-and-upload
        with:
          version-number: ${{ github.event.release.tag_name }}
          retention-days: 1

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      actions: read
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: ${{ github.event.release.tag_name }}
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b
        with:
          attestations: true
